import { createHash } from "node:crypto";
import {
  GENERATED_MIGRATION_FINGERPRINT,
  GENERATED_MIGRATION_VERSIONS,
} from "../../../shared/io/generated/entity-specs.js";

/**
 * Fails loudly when the database's applied migrations differ from the ones the
 * envelope specs were generated against. The specs are generated by
 * introspecting the schema (scripts/generate-envelope-types.ts), so a migration
 * applied without regenerating them would silently desync the two — this refuses
 * to run until they are regenerated. It takes the already-loaded applied
 * migrations (the raw `schema_migrations` read stays inside the database
 * package) and hashes their versions the same way the generator did.
 */
export function assertGeneratedSchemaCurrent(
  appliedMigrations: readonly { version: string }[],
): void {
  const versions = appliedMigrations.map((migration) => migration.version);
  const fingerprint = createHash("sha256")
    .update(versions.join("\n"))
    .digest("hex");

  if (fingerprint !== GENERATED_MIGRATION_FINGERPRINT) {
    throw new Error(
      [
        "Database schema is out of sync with the generated envelope specs: the",
        "applied migrations differ from those the specs were generated against.",
        `  specs generated against: ${GENERATED_MIGRATION_VERSIONS.join(", ")}`,
        `  database has:            ${versions.join(", ")}`,
        "Run `npm run generate:envelope-types` to regenerate the envelope specs.",
      ].join("\n"),
    );
  }
}
