import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  IMPORT_ARTIFACT_KINDS,
  IMPORT_OPERATIONS,
  IMPORT_OPERATION_SUFFIXES,
  type ImportArtifactKind,
  type ImportOperation,
  importTypeMetadata,
} from "../src/shared/io/import-type-metadata.js";

const outputDirectory = path.join(
  process.cwd(),
  "src",
  "shared",
  "io",
  "generated",
);
const importMutationOutputDirectory = path.join(
  process.cwd(),
  "src",
  "cli",
  "import",
  "artifacts",
  "io",
  "generated-mutations",
);

function generatedHeader(): string {
  return [
    "/* eslint-disable */",
    "// Generated by scripts/generate-envelope-types.ts. Do not edit.",
    "",
  ].join("\n");
}

function entitySpecsModule(): string {
  return `${generatedHeader()}import { z } from "zod";

const nonEmptyString = z.string().trim().min(1);
const nullableNonEmptyString = nonEmptyString.nullable();

const LocationPathCentroidSpec = z
  .object({
    type: z.literal("Point"),
    coordinates: z.tuple([
      z.coerce.number().finite(),
      z.coerce.number().finite(),
    ]),
  })
  .strict();

const LocationPathBboxSpec = z
  .object({
    type: z.literal("Polygon"),
    coordinates: z.tuple([
      z.tuple([
        z.tuple([z.coerce.number().finite(), z.coerce.number().finite()]),
        z.tuple([z.coerce.number().finite(), z.coerce.number().finite()]),
        z.tuple([z.coerce.number().finite(), z.coerce.number().finite()]),
        z.tuple([z.coerce.number().finite(), z.coerce.number().finite()]),
        z.tuple([z.coerce.number().finite(), z.coerce.number().finite()]),
      ]),
    ]),
  })
  .strict()
  .superRefine((bbox, context) => {
    const ring = bbox.coordinates[0];
    const [firstLng, firstLat] = ring[0];
    const [lastLng, lastLat] = ring[4];
    if (firstLng !== lastLng || firstLat !== lastLat) {
      context.addIssue({
        code: "custom",
        path: ["coordinates", 0, 4],
        message: "must close the polygon ring",
      });
    }
  });

export const LocationPathSpec = z
  .object({
    location_path_id: nonEmptyString,
    path: nonEmptyString,
    level: z.enum(["state", "administrative_area", "place"]),
    state_or_territory_slug: nonEmptyString,
    administrative_area_slug: nullableNonEmptyString,
    place_slug: nullableNonEmptyString,
    state_or_territory_name: nonEmptyString,
    administrative_area_name: nullableNonEmptyString,
    place_name: nullableNonEmptyString,
    parent_location_path_id: nullableNonEmptyString,
    centroid: LocationPathCentroidSpec.nullable().optional(),
    bbox: LocationPathBboxSpec.nullable().optional(),
  })
  .strict()
  .superRefine((row, context) => {
    if (row.level === "state") {
      for (const fieldName of [
        "administrative_area_slug",
        "place_slug",
        "administrative_area_name",
        "place_name",
        "parent_location_path_id",
      ] as const) {
        if (row[fieldName] !== null) {
          context.addIssue({
            code: "custom",
            path: [fieldName],
            message: "must be null for state location paths",
          });
        }
      }
    }

    if (row.level === "administrative_area") {
      for (const fieldName of [
        "administrative_area_slug",
        "administrative_area_name",
        "parent_location_path_id",
      ] as const) {
        if (row[fieldName] === null) {
          context.addIssue({
            code: "custom",
            path: [fieldName],
            message: "is required for administrative area location paths",
          });
        }
      }
      for (const fieldName of ["place_slug", "place_name"] as const) {
        if (row[fieldName] !== null) {
          context.addIssue({
            code: "custom",
            path: [fieldName],
            message: "must be null for administrative area location paths",
          });
        }
      }
    }

    if (row.level === "place") {
      for (const fieldName of [
        "administrative_area_slug",
        "place_slug",
        "administrative_area_name",
        "place_name",
        "parent_location_path_id",
      ] as const) {
        if (row[fieldName] === null) {
          context.addIssue({
            code: "custom",
            path: [fieldName],
            message: "is required for place location paths",
          });
        }
      }
    }
  });

export const LocationPathCreateSpec = LocationPathSpec;

export const LocationPathGeometrySpec = z
  .object({
    location_path_id: nonEmptyString,
    geometry: z.unknown(),
    sourceLocationPathKey: nonEmptyString,
    selectedYear: z.union([z.string(), z.number()]).optional(),
  })
  .strict();

export const LocationPathGeometryCreateSpec = LocationPathGeometrySpec;

export const LocationPathAliasSpec = z
  .object({
    alias_path: nonEmptyString,
    location_path_id: nonEmptyString,
    selectedYear: z.union([z.string(), z.number()]).optional(),
  })
  .strict();

export const LocationPathAliasCreateSpec = LocationPathAliasSpec;

export const AgencySpec = z
  .object({
    id: nonEmptyString.optional(),
    name: nonEmptyString,
    city: z.string().nullable().optional(),
    state: nonEmptyString,
    address: z.string().nullable().optional(),
    zip_code: z.string().nullable().optional(),
    contact_name: z.string().nullable().optional(),
    contact_email: z.string().nullable().optional(),
    slug: nonEmptyString.optional(),
    location_path_id: nonEmptyString.optional(),
    latitude: z.number().finite().optional(),
    longitude: z.number().finite().optional(),
    addresses: z.record(z.string(), z.unknown()).optional(),
    emails: z.record(z.string(), z.unknown()).optional(),
    location: z.record(z.string(), z.unknown()).optional(),
    phones: z.record(z.string(), z.unknown()).optional(),
    urls: z.record(z.string(), z.unknown()).optional(),
  })
  .strict();

export const AgencyCreateSpec = AgencySpec.extend({
  id: nonEmptyString,
  slug: nonEmptyString,
  location_path_id: nonEmptyString,
  latitude: z.number().finite(),
  longitude: z.number().finite(),
});

export const PersonnelSpec = z
  .object({
    id: nonEmptyString.optional(),
    first_name: nonEmptyString,
    last_name: nonEmptyString,
    middle_name: z.string().nullable().optional(),
    prefix: z.string().nullable().optional(),
    suffix: z.string().nullable().optional(),
    slug: nonEmptyString.optional(),
  })
  .strict();

export const PersonnelCreateSpec = PersonnelSpec.extend({
  id: nonEmptyString,
  slug: nonEmptyString,
});

export const AgencyPersonnelSpec = z
  .object({
    id: nonEmptyString.optional(),
    agency_id: nonEmptyString,
    personnel_id: nonEmptyString,
    badge_number: z.string().nullable().optional(),
    start_date: nonEmptyString,
    end_date: z.string().nullable().optional(),
    title: z.string().nullable().optional(),
  })
  .strict();

export const AgencyPersonnelCreateSpec = AgencyPersonnelSpec.extend({
  id: nonEmptyString,
});
`;
}

function envelopeSupport(label: string): string {
  return `
type EnvelopeReadRef =
  | { path: string; kind?: string; sha256?: string }
  | { ref: { path: string; kind?: string; sha256?: string } };

type EnvelopeReadOptions = {
  expectedNamespace?: string;
  relativeTo?: string;
};

function formatError(error: z.ZodError): string {
  return \`${label} is malformed at \${firstIssuePath(error)}.\`;
}

function refValue(pathOrRef: string | EnvelopeReadRef): {
  path: string;
  kind?: string;
  sha256?: string;
} {
  if (typeof pathOrRef === "string") {
    return { path: pathOrRef };
  }
  if ("ref" in pathOrRef) {
    return pathOrRef.ref;
  }
  return pathOrRef;
}

function resolveReadPath(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions,
): { filePath: string; kind?: string; sha256?: string } {
  const ref = refValue(pathOrRef);
  if (typeof pathOrRef === "string" || path.isAbsolute(ref.path)) {
    return { ...ref, filePath: ref.path };
  }
  if (options.relativeTo === undefined || options.relativeTo.trim().length === 0) {
    throw new Error(\`Relative \${ref.kind ?? "${label}"} ref requires relativeTo.\`);
  }

  const baseDirectory = path.dirname(options.relativeTo);
  const resolvedPath = path.resolve(baseDirectory, ref.path);
  const relativePath = path.relative(baseDirectory, resolvedPath);
  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new Error(\`\${ref.kind ?? "${label}"} ref.path escapes its directory: \${ref.path}\`);
  }
  return { ...ref, filePath: resolvedPath };
}
`;
}

function artifactModule(kind: ImportArtifactKind): string {
  const recordKind = importTypeMetadata[kind].recordKind;
  const recordSpecName = recordKind;
  const supportsRecordEnvelope = recordKind !== kind;
  const recordItemSchema = supportsRecordEnvelope
    ? `const recordReferenceSchema = z
  .object({
    ref: z
      .object({
        path: z.string().trim().min(1),
        kind: z.literal("${recordKind}"),
        sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(),
      })
      .strict(),
  })
  .strict();
const inlineRecordItemSchema = z
  .object({ spec: ${recordSpecName}Spec })
  .strict();
const recordItemSchema = z.union([recordReferenceSchema, inlineRecordItemSchema]);`
    : `const recordItemSchema = z
  .object({ spec: ${recordSpecName}Spec })
  .strict();`;
  const singularRecordSchema = supportsRecordEnvelope
    ? `
export const recordSchema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("${recordKind}"),
    metadata: z
      .object({
        name: z.string().trim().min(1),
        namespace: z.string().trim().min(1),
        labels: z.record(z.string(), z.string()).optional(),
        annotations: z.record(z.string(), z.string()).optional(),
      })
      .strict(),
    spec: ${recordSpecName}Spec,
  })
  .strict();

export type ${recordKind}Envelope = z.infer<typeof recordSchema>;
export type ${recordKind}Input = Omit<${recordKind}Envelope, "apiVersion" | "kind">;

function parse${recordKind}(value: unknown): ${recordKind}Envelope {
  const result = recordSchema.safeParse(value);
  if (!result.success) {
    throw new Error(\`${recordKind} is malformed at \${firstIssuePath(result.error)}.\`);
  }
  return result.data;
}

function new${recordKind}(input: ${recordKind}Input): ${recordKind}Envelope {
  return parse${recordKind}({
    apiVersion: INTAKE_API_VERSION,
    kind: "${recordKind}",
    ...input,
  });
}

async function read${recordKind}(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions = {},
): Promise<${recordKind}Envelope> {
  const ref = resolveReadPath(pathOrRef, options);
  if (ref.kind !== undefined && ref.kind !== "${recordKind}") {
    throw new Error(\`${recordKind} ref.kind \${ref.kind} does not match expected kind ${recordKind}: \${ref.filePath}\`);
  }
  const { contents, document } = await readYamlDocumentFile(ref.filePath, "${recordKind}");
  if (ref.sha256 !== undefined && yamlDigest(contents) !== ref.sha256) {
    throw new Error(\`${recordKind} sha256 mismatch: \${ref.filePath}\`);
  }
  const envelope = parse${recordKind}(document);
  if (
    options.expectedNamespace !== undefined &&
    envelope.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`${recordKind} namespace \${envelope.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${ref.filePath}\`,
    );
  }
  return envelope;
}

async function write${recordKind}(
  directory: string,
  envelope: ${recordKind}Envelope,
): Promise<{ path: string; sha256: string }> {
  const parsed = parse${recordKind}(envelope);
  const filePath = yamlResourcePath(directory, parsed);
  const contents = await writeYamlDocumentFile(filePath, parsed);
  return { path: filePath, sha256: yamlDigest(contents) };
}
`
    : "";
  const readRecords = supportsRecordEnvelope
    ? `    if ("ref" in recordItem) {
      const record = await read${recordKind}(recordItem.ref, {
        relativeTo: filePath,
        expectedNamespace: artifact.metadata.namespace,
      });
      if (record.metadata.name !== recordKey) {
        throw new Error(
          \`${kind} record metadata.name \${record.metadata.name} does not match expected record key \${recordKey}: \${filePath}\`,
        );
      }
      records[recordKey] = validateRecord(filePath, recordKey, record.spec);
    } else {
      records[recordKey] = validateRecord(filePath, recordKey, recordItem.spec);
    }`
    : `    records[recordKey] = validateRecord(filePath, recordKey, recordItem.spec);`;
  const externalizeRecords = supportsRecordEnvelope
    ? `  if (options.externalizeRecords === true) {
    const recordsDirectory =
      options.recordsDirectory ??
      \`\${path.basename(artifactPath, path.extname(artifactPath))}.records\`;
    const records: Record<string, { ref: { path: string; kind: "${recordKind}"; sha256?: string } }> = {};

    for (const [recordKey, recordItem] of Object.entries(artifact.spec.records)) {
      if ("ref" in recordItem) {
        records[recordKey] = recordItem;
        continue;
      }
      const record = new${recordKind}({
        metadata: {
          name: recordKey,
          namespace: artifact.metadata.namespace,
        },
        spec: recordItem.spec,
      });
      const recordPath = path.join(
        path.dirname(artifactPath),
        recordsDirectory,
        yamlResourceFileName(recordKey, "${recordKind}"),
      );
      const contents = await writeYamlDocumentFile(recordPath, record);
      records[recordKey] = {
        ref: {
          path: path.relative(path.dirname(artifactPath), recordPath),
          kind: "${recordKind}",
          sha256: yamlDigest(contents),
        },
      };
    }

    artifact = new${kind}({
      metadata: artifact.metadata,
      spec: {
        ...artifact.spec,
        records,
      },
    });
  }`
    : `  if (options.externalizeRecords === true) {
    throw new Error("${kind} does not support externalized singular record envelopes.");
  }`;
  const singularRecordExport = supportsRecordEnvelope
    ? `
export const ${recordKind} = {
  kind: "${recordKind}",
  schema: recordSchema,
  new: new${recordKind},
  read: read${recordKind},
  write: write${recordKind},
};
`
    : "";
  return `${generatedHeader()}import path from "node:path";
import { z } from "zod";
import { INTAKE_API_VERSION } from "../import-types.js";
import {
  firstIssuePath,
  yamlDigest,
  yamlResourceFileName,
  yamlResourcePath,
} from "../resource.js";
import {
  readYamlDocumentFile,
  writeYamlDocumentFile,
} from "../internal/yaml-document.js";
import { ${recordSpecName}Spec } from "./entity-specs.js";
export { ${recordSpecName}Spec } from "./entity-specs.js";

${envelopeSupport(kind)}

const metadataSchema = z
  .object({
    name: z.string().trim().min(1),
    namespace: z.string().trim().min(1),
    labels: z.record(z.string(), z.string()).optional(),
    annotations: z.record(z.string(), z.string()).optional(),
    createdAt: z.string().trim().min(1).optional(),
    producedAt: z.string().trim().min(1).optional(),
    producer: z.string().trim().min(1).optional(),
  })
  .strict();

${recordItemSchema}

export const schema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("${kind}"),
    metadata: metadataSchema,
    spec: z
      .object({
        warnings: z.array(z.string()).optional(),
        audit: z.record(z.string(), z.unknown()).optional(),
        records: z.record(z.string(), recordItemSchema),
      })
      .strict(),
  })
  .strict();

export type ${kind}Envelope = z.infer<typeof schema>;
export type ${kind}Input = Omit<${kind}Envelope, "apiVersion" | "kind">;
export type ${kind}ResolvedEnvelope = Omit<${kind}Envelope, "spec"> & {
  spec: Omit<${kind}Envelope["spec"], "records"> & {
    records: Record<string, z.infer<typeof ${recordKind}Spec>>;
  };
};

export type ImportArtifactWriteOptions = {
  externalizeRecords?: boolean;
  recordsDirectory?: string;
};

function parse${kind}(value: unknown): ${kind}Envelope {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new Error(formatError(result.error));
  }
  return result.data;
}

function new${kind}(input: ${kind}Input): ${kind}Envelope {
  return parse${kind}({
    apiVersion: INTAKE_API_VERSION,
    kind: "${kind}",
    ...input,
  });
}

function validateRecord(
  artifactPath: string,
  recordKey: string,
  value: unknown,
): z.infer<typeof ${recordSpecName}Spec> {
  const result = ${recordSpecName}Spec.safeParse(value);
  if (!result.success) {
    throw new Error(
      \`${kind} record \${recordKey} is malformed at \${firstIssuePath(result.error)}: \${artifactPath}\`,
    );
  }
  return result.data;
}

${singularRecordSchema}

async function read${kind}(
  filePath: string,
  options: EnvelopeReadOptions & {
    expectedKind?: "${kind}";
    expectedSha256?: string;
    raw: true;
  },
): Promise<${kind}Envelope>;
async function read${kind}(
  filePath: string,
  options?: EnvelopeReadOptions & {
    expectedKind?: "${kind}";
    expectedSha256?: string;
    raw?: false;
  },
): Promise<${kind}ResolvedEnvelope>;
async function read${kind}(
  filePath: string,
  options: EnvelopeReadOptions & {
    expectedKind?: "${kind}";
    expectedSha256?: string;
    raw?: boolean;
  } = {},
): Promise<${kind}Envelope | ${kind}ResolvedEnvelope> {
  const { contents, document } = await readYamlDocumentFile(filePath, "${kind}");
  if (options.expectedSha256 !== undefined && yamlDigest(contents) !== options.expectedSha256) {
    throw new Error(\`${kind} sha256 mismatch: \${filePath}\`);
  }
  const artifact = parse${kind}(document);
  if (options.expectedKind !== undefined && artifact.kind !== options.expectedKind) {
    throw new Error(\`${kind} kind \${artifact.kind} does not match expected kind \${options.expectedKind}: \${filePath}\`);
  }
  if (
    options.expectedNamespace !== undefined &&
    artifact.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`${kind} namespace \${artifact.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${filePath}\`,
    );
  }
  if (options.raw === true) {
    return artifact;
  }

  const records: Record<string, z.infer<typeof ${recordSpecName}Spec>> = {};
  for (const [recordKey, recordItem] of Object.entries(artifact.spec.records)) {
${readRecords}
  }

  return {
    ...artifact,
    spec: {
      ...artifact.spec,
      records,
    },
  };
}

async function write${kind}(
  directory: string,
  envelope: ${kind}Input,
  options: ImportArtifactWriteOptions = {},
): Promise<{ path: string; sha256: string }> {
  let artifact = new${kind}(envelope);
  const artifactPath = yamlResourcePath(directory, artifact);

${externalizeRecords}

  const contents = await writeYamlDocumentFile(artifactPath, artifact);
  return { path: artifactPath, sha256: yamlDigest(contents) };
}

export const ${kind} = {
  kind: "${kind}",
  schema,
  new: new${kind},
  read: read${kind},
  write: write${kind},
};

${singularRecordExport}

export const read = read${kind};
export const write = write${kind};
`;
}

function artifactsModule(): string {
  const artifactImports = IMPORT_ARTIFACT_KINDS.map(
    (kind) => `import { ${kind} } from "./${kind}.js";`,
  ).join("\n");
  const artifactSpecSchemas = IMPORT_ARTIFACT_KINDS.map(
    (kind) => `  ${kind}: ${kind}.schema.shape.spec,`,
  ).join("\n");
  return `${generatedHeader()}import path from "node:path";
import { z } from "zod";
import { INTAKE_API_VERSION, IMPORT_ARTIFACT_KINDS } from "../import-types.js";
import {
  firstIssuePath,
  yamlDigest,
  yamlResourcePath,
} from "../resource.js";
import {
  readYamlDocumentFile,
  writeYamlDocumentFile,
} from "../internal/yaml-document.js";
${artifactImports}

${envelopeSupport("Artifacts")}

const metadataSchema = z
  .object({
    name: z.string().trim().min(1),
    namespace: z.string().trim().min(1),
    labels: z.record(z.string(), z.string()).optional(),
    annotations: z.record(z.string(), z.string()).optional(),
    producedAt: z.string().trim().min(1).optional(),
    producer: z.string().trim().min(1).optional(),
  })
  .strict();

const artifactKindSchema = z.enum(IMPORT_ARTIFACT_KINDS);
const artifactSpecSchemas: Record<string, z.ZodType> = {
${artifactSpecSchemas}
};
const artifactReferenceSchema = z
  .object({
    ref: z
      .object({
        path: z.string().trim().min(1),
        kind: artifactKindSchema,
        sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(),
      })
      .strict(),
  })
  .strict();
const inlineArtifactSchema = z
  .object({
    kind: artifactKindSchema,
    spec: z.record(z.string(), z.unknown()),
  })
  .strict()
  .superRefine((artifact, context) => {
    const specSchema = artifactSpecSchemas[artifact.kind];
    const result = specSchema.safeParse(artifact.spec);
    if (!result.success) {
      for (const issue of result.error.issues) {
        context.addIssue({ ...issue, path: ["spec", ...issue.path] });
      }
    }
  });

export const schema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("Artifacts"),
    metadata: metadataSchema,
    spec: z
      .object({
        artifacts: z
          .array(
            z.union([artifactReferenceSchema, inlineArtifactSchema]),
          ),
      })
      .strict(),
  })
  .strict();

export type ArtifactsEnvelope = z.infer<typeof schema>;
export type ArtifactsInput = Omit<z.infer<typeof schema>, "apiVersion" | "kind">;

function parseArtifacts(value: unknown): ArtifactsEnvelope {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new Error(formatError(result.error));
  }
  return result.data;
}

function newArtifacts(input: ArtifactsInput): ArtifactsEnvelope {
  return parseArtifacts({
    apiVersion: INTAKE_API_VERSION,
    kind: "Artifacts",
    ...input,
  });
}

async function readArtifacts(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions = {},
): Promise<ArtifactsEnvelope> {
  const ref = resolveReadPath(pathOrRef, options);
  if (ref.kind !== undefined && ref.kind !== "Artifacts") {
    throw new Error(\`Artifacts ref.kind \${ref.kind} does not match expected kind Artifacts: \${ref.filePath}\`);
  }
  const { contents, document } = await readYamlDocumentFile(ref.filePath, "Artifacts");
  if (ref.sha256 !== undefined && yamlDigest(contents) !== ref.sha256) {
    throw new Error(\`Artifacts sha256 mismatch: \${ref.filePath}\`);
  }
  const envelope = parseArtifacts(document);
  if (
    options.expectedNamespace !== undefined &&
    envelope.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`Artifacts namespace \${envelope.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${ref.filePath}\`,
    );
  }
  return envelope;
}

async function writeArtifacts(
  directory: string,
  envelope: ArtifactsEnvelope,
): Promise<{ path: string }> {
  const parsed = parseArtifacts(envelope);
  const filePath = yamlResourcePath(directory, parsed);
  await writeYamlDocumentFile(filePath, parsed);
  return { path: filePath };
}

export const Artifacts = {
  kind: "Artifacts",
  schema,
  new: newArtifacts,
  read: readArtifacts,
  write: writeArtifacts,
};

export async function read(
  filePath: string,
  options: Parameters<typeof Artifacts.read>[1] = {},
) {
  return Artifacts.read(filePath, options);
}

export async function write(directory: string, envelope: ArtifactsInput) {
  return Artifacts.write(directory, Artifacts.new(envelope));
}
`;
}

function mutationKind(recordKind: string, operation: ImportOperation): string {
  return `${recordKind}${IMPORT_OPERATION_SUFFIXES[operation]}`;
}

function specName(kind: ImportArtifactKind): string {
  return importTypeMetadata[kind].recordKind;
}

function mutationSpecExpression(
  specBaseName: string,
  operation: ImportOperation,
): string {
  if (operation === "create") {
    return `${specBaseName}CreateSpec`;
  }
  if (operation === "update") {
    return `z
  .object({
    operations: z.array(operationSchema).min(1),
  })
  .strict()`;
  }
  return "z.object({}).strict()";
}

function mutationModule(
  kind: ImportArtifactKind,
  operation: ImportOperation,
): string {
  const recordKind = importTypeMetadata[kind].recordKind;
  const specBaseName = specName(kind);
  const envelopeKind = mutationKind(recordKind, operation);
  const specImport =
    operation === "create" || operation === "update"
      ? `import { ${specBaseName}Spec${operation === "create" ? `, ${specBaseName}CreateSpec` : ""} } from "../../../../../shared/io/generated/entity-specs.js";\n`
      : "";
  const operationImport = "";
  const updateValidation =
    operation === "update"
      ? `
const fieldSchemas = (${specBaseName}Spec as z.ZodObject<z.ZodRawShape>).shape;
const fieldNames = Object.keys(fieldSchemas);
const fieldSchemaByName: Record<string, { safeParse(value: unknown): { success: true } | { success: false; error: z.ZodError } }> = fieldSchemas as unknown as Record<string, { safeParse(value: unknown): { success: true } | { success: false; error: z.ZodError } }>;

const mutationOperationSourceSchema = z
  .object({
    namespace: z.string().trim().min(1),
    command: z
      .object({
        name: z.string().trim().min(1),
      })
      .strict(),
    kind: z.string().trim().min(1),
    name: z.string().trim().min(1),
  })
  .strict();

const mutationOperationEvidenceSchema = z.array(z.record(z.string(), z.unknown()));

const mutationOperationBaseSchema = z
  .object({
    path: z
      .string()
      .trim()
      .min(1)
      .refine((value) => value.split(".").every((part) => part.length > 0), {
        message: "Path segments must not be empty",
      }),
    reason: z.string().trim().min(1),
    source: mutationOperationSourceSchema,
    evidence: mutationOperationEvidenceSchema.optional(),
  })
  .strict();

const operationSchema = z.union([
  mutationOperationBaseSchema.extend({
    action: z.literal("set"),
    from: z.unknown(),
    to: z.unknown(),
  }).strict(),
  mutationOperationBaseSchema.extend({
    action: z.literal("check"),
    value: z.unknown(),
  }).strict(),
]).superRefine(
  (operation, context) => {
    if (operation.path.includes(".")) {
      context.addIssue({
        code: "custom",
        path: ["path"],
        message: "must be a ${recordKind} field",
      });
      return;
    }
    const fieldSchema = fieldSchemaByName[operation.path];
    if (fieldSchema === undefined) {
      context.addIssue({
        code: "custom",
        path: ["path"],
        message: \`must be one of \${fieldNames.join(", ")}\`,
      });
      return;
    }
    if (operation.action === "set") {
      for (const propertyName of ["from", "to"] as const) {
        const result = fieldSchema.safeParse(operation[propertyName]);
        if (!result.success) {
          for (const issue of result.error.issues) {
            context.addIssue({ ...issue, path: [propertyName, ...issue.path] });
          }
        }
      }
      return;
    }

    const result = fieldSchema.safeParse(operation.value);
    if (!result.success) {
      for (const issue of result.error.issues) {
        context.addIssue({ ...issue, path: ["value", ...issue.path] });
      }
    }
  },
);
`
      : "";
  return `${generatedHeader()}import path from "node:path";
import { z } from "zod";
import { INTAKE_API_VERSION } from "../../../../../shared/io/import-types.js";
import {
  firstIssuePath,
  yamlDigest,
  yamlResourcePath,
} from "../../../../../shared/io/resource.js";
import {
  readYamlDocumentFile,
  writeYamlDocumentFile,
} from "../../../../../shared/io/internal/yaml-document.js";
${specImport}${operationImport}
${envelopeSupport(envelopeKind)}
const metadataSchema = z
  .object({
    name: z.string().trim().min(1),
    namespace: z.string().trim().min(1),
    labels: z.record(z.string(), z.string()).optional(),
    annotations: z.record(z.string(), z.string()).optional(),
  })
  .strict();

${updateValidation}

export const specSchema = ${mutationSpecExpression(specBaseName, operation)};

export const schema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("${envelopeKind}"),
    metadata: metadataSchema,
    spec: specSchema,
  })
  .strict();

export type ${envelopeKind}Envelope = z.infer<typeof schema>;
export type ${envelopeKind}Input = Omit<${envelopeKind}Envelope, "apiVersion" | "kind">;

function parse${envelopeKind}(value: unknown): ${envelopeKind}Envelope {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new Error(formatError(result.error));
  }
  return result.data;
}

function new${envelopeKind}(input: ${envelopeKind}Input): ${envelopeKind}Envelope {
  return parse${envelopeKind}({
    apiVersion: INTAKE_API_VERSION,
    kind: "${envelopeKind}",
    ...input,
  });
}

async function read${envelopeKind}(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions = {},
): Promise<${envelopeKind}Envelope> {
  const ref = resolveReadPath(pathOrRef, options);
  if (ref.kind !== undefined && ref.kind !== "${envelopeKind}") {
    throw new Error(\`${envelopeKind} ref.kind \${ref.kind} does not match expected kind ${envelopeKind}: \${ref.filePath}\`);
  }
  const { contents, document } = await readYamlDocumentFile(ref.filePath, "${envelopeKind}");
  if (ref.sha256 !== undefined && yamlDigest(contents) !== ref.sha256) {
    throw new Error(\`${envelopeKind} sha256 mismatch: \${ref.filePath}\`);
  }
  const envelope = parse${envelopeKind}(document);
  if (
    options.expectedNamespace !== undefined &&
    envelope.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`${envelopeKind} namespace \${envelope.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${ref.filePath}\`,
    );
  }
  return envelope;
}

async function write${envelopeKind}(
  directory: string,
  envelope: ${envelopeKind}Envelope,
): Promise<{ path: string }> {
  const parsed = parse${envelopeKind}(envelope);
  const filePath = yamlResourcePath(directory, parsed);
  await writeYamlDocumentFile(filePath, parsed);
  return { path: filePath };
}

export const ${envelopeKind} = {
  kind: "${envelopeKind}",
  schema,
  new: new${envelopeKind},
  read: read${envelopeKind},
  write: write${envelopeKind},
};
`;
}

function mutationIndexModule(): string {
  const imports: string[] = [];
  const mapItems: string[] = [];
  for (const kind of IMPORT_ARTIFACT_KINDS.filter(
    (candidate) => "targetTable" in importTypeMetadata[candidate],
  )) {
    const recordKind = importTypeMetadata[kind].recordKind;
    for (const operation of IMPORT_OPERATIONS) {
      const envelopeKind = mutationKind(recordKind, operation);
      imports.push(`import { ${envelopeKind} } from "./${envelopeKind}.js";`);
      mapItems.push(`  ${envelopeKind},`);
    }
  }
  return `${generatedHeader()}${imports.join("\n")}

export const importMutationEnvelopeTypes = {
${mapItems.join("\n")}
};
`;
}

function indexModule(): string {
  const artifactExports = IMPORT_ARTIFACT_KINDS.map((kind) => {
    const recordKind = importTypeMetadata[kind].recordKind;
    if (recordKind === kind) {
      return `export { ${kind}, ${recordKind}Spec } from "./${kind}.js";
export type { ${kind}Envelope, ${kind}Input } from "./${kind}.js";`;
    }
    return `export { ${kind}, ${recordKind}, ${recordKind}Spec } from "./${kind}.js";
export type { ${kind}Envelope, ${kind}Input, ${recordKind}Envelope, ${recordKind}Input } from "./${kind}.js";`;
  }).join("\n");
  return `${generatedHeader()}export { Artifacts } from "./Artifacts.js";
export type { ArtifactsEnvelope, ArtifactsInput } from "./Artifacts.js";
${artifactExports}
`;
}

await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });
await rm(importMutationOutputDirectory, { recursive: true, force: true });
await mkdir(importMutationOutputDirectory, { recursive: true });
await writeFile(
  path.join(outputDirectory, "entity-specs.ts"),
  entitySpecsModule(),
);
await writeFile(path.join(outputDirectory, "Artifacts.ts"), artifactsModule());
for (const kind of IMPORT_ARTIFACT_KINDS) {
  await writeFile(
    path.join(outputDirectory, `${kind}.ts`),
    artifactModule(kind),
  );
  if (!("targetTable" in importTypeMetadata[kind])) {
    continue;
  }
  for (const operation of IMPORT_OPERATIONS) {
    await writeFile(
      path.join(
        importMutationOutputDirectory,
        `${mutationKind(importTypeMetadata[kind].recordKind, operation)}.ts`,
      ),
      mutationModule(kind, operation),
    );
  }
}
await writeFile(path.join(outputDirectory, "index.ts"), indexModule());
await writeFile(
  path.join(importMutationOutputDirectory, "index.ts"),
  mutationIndexModule(),
);

console.log(`Generated envelope types in ${outputDirectory}`);
