import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { introspectSchema } from "./lib/schema-introspection.js";
import { ENTITY_TABLES } from "./lib/entity-spec-generator.js";
import { generateDataRequestDoc } from "./lib/data-request-doc-generator.js";

const databaseUrl = process.env.DATABASE_URL;
if (databaseUrl === undefined || databaseUrl.trim() === "") {
  throw new Error(
    "DATABASE_URL is required: supported import fields in the data-request document are generated by introspecting the database schema.",
  );
}

const [rawDataRequestModel, dataChecklist, standardRequest] = await Promise.all(
  [
    readFile(
      new URL("./templates/raw-data-request.md", import.meta.url),
      "utf8",
    ),
    readFile(
      new URL("./templates/iacp-data-checklist.md", import.meta.url),
      "utf8",
    ),
    readFile(
      new URL("./templates/standard-data-request.md", import.meta.url),
      "utf8",
    ),
  ],
);
const schema = await introspectSchema(databaseUrl, ENTITY_TABLES);
const outputPath = path.join(process.cwd(), "docs", "data-request-format.md");
await writeFile(
  outputPath,
  generateDataRequestDoc(
    schema,
    rawDataRequestModel,
    dataChecklist,
    standardRequest,
  ),
);
console.log(`Wrote ${outputPath}`);
