import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  IMPORT_OPERATIONS,
  IMPORT_OPERATION_SUFFIXES,
  type ImportOperation,
} from "../src/shared/io/import-operations.js";
import { introspectSchema } from "./lib/schema-introspection.js";
import {
  ENTITY_TABLES,
  IMPORT_ARTIFACT_KINDS,
  RECORD_KIND_BY_ARTIFACT_KIND,
  generateEntitySpecsModule,
} from "./lib/entity-spec-generator.js";

// The generator sources the kind list from the descriptors, never from its own
// generated output — the plural artifact kind is just a string here.
type ImportArtifactKind = string;

const outputDirectory = path.join(
  process.cwd(),
  "src",
  "shared",
  "io",
  "generated",
);
const importMutationOutputDirectory = path.join(
  process.cwd(),
  "src",
  "cli",
  "import",
  "artifacts",
  "io",
  "generated-mutations",
);

// Kinds whose records are written one-file-per-record (a `.records` directory
// of singular record envelopes plus a small envelope-of-refs). Every import
// kind currently participates; the set is explicit so the intent is clear and
// a kind can be opted out without reintroducing the `recordKind !== kind`
// heuristic.
const RECORD_ENVELOPE_KINDS = new Set<ImportArtifactKind>([
  "LocationPaths",
  "LocationPathGeometries",
  "LocationPathAliases",
  "Agencies",
  "Personnel",
  "AgencyPersonnel",
  "LicensingAuthorities",
  "AuthorityLicenses",
  "Licenses",
  "LicenseActions",
]);

function supportsRecordEnvelopeFor(kind: ImportArtifactKind): boolean {
  return RECORD_ENVELOPE_KINDS.has(kind);
}

// The singular per-record envelope kind. It is usually the metadata
// `recordKind` (Agency, LocationPathGeometry, ...), but when the record kind is
// spelled identically to the plural artifact kind (Personnel, AgencyPersonnel)
// a distinct name is required so the generated singular writer/reader/types do
// not collide with the plural ones. The metadata `recordKind` is left untouched
// because the DatabaseMutations kinds derive from it.
function recordEnvelopeKindFor(kind: ImportArtifactKind): string {
  const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
  return recordKind === kind ? `${recordKind}Record` : recordKind;
}

function generatedHeader(): string {
  return [
    "/* eslint-disable */",
    "// Generated by scripts/generate-envelope-types.ts. Do not edit.",
    "",
  ].join("\n");
}

function envelopeSupport(label: string): string {
  return `
type EnvelopeReadRef =
  | { path: string; kind?: string; sha256?: string }
  | { ref: { path: string; kind?: string; sha256?: string } };

type EnvelopeReadOptions = {
  expectedNamespace?: string;
  relativeTo?: string;
};

function formatError(error: z.ZodError): string {
  return \`${label} is malformed at \${firstIssuePath(error)}.\`;
}

function refValue(pathOrRef: string | EnvelopeReadRef): {
  path: string;
  kind?: string;
  sha256?: string;
} {
  if (typeof pathOrRef === "string") {
    return { path: pathOrRef };
  }
  if ("ref" in pathOrRef) {
    return pathOrRef.ref;
  }
  return pathOrRef;
}

function resolveReadPath(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions,
): { filePath: string; kind?: string; sha256?: string } {
  const ref = refValue(pathOrRef);
  if (typeof pathOrRef === "string" || path.isAbsolute(ref.path)) {
    return { ...ref, filePath: ref.path };
  }
  if (options.relativeTo === undefined || options.relativeTo.trim().length === 0) {
    throw new Error(\`Relative \${ref.kind ?? "${label}"} ref requires relativeTo.\`);
  }

  const baseDirectory = path.dirname(options.relativeTo);
  const resolvedPath = path.resolve(baseDirectory, ref.path);
  const relativePath = path.relative(baseDirectory, resolvedPath);
  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new Error(\`\${ref.kind ?? "${label}"} ref.path escapes its directory: \${ref.path}\`);
  }
  return { ...ref, filePath: resolvedPath };
}
`;
}

function artifactModule(kind: ImportArtifactKind): string {
  const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
  const recordSpecName = recordKind;
  const supportsRecordEnvelope = supportsRecordEnvelopeFor(kind);
  const recordEnvelopeKind = recordEnvelopeKindFor(kind);
  const recordItemSchema = supportsRecordEnvelope
    ? `const recordReferenceSchema = z
  .object({
    ref: z
      .object({
        path: z.string().trim().min(1),
        kind: z.literal("${recordEnvelopeKind}"),
        sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(),
      })
      .strict(),
  })
  .strict();
const inlineRecordItemSchema = z
  .object({
    metadata: recordMetadataSchema.optional(),
    spec: z.record(z.string(), z.unknown()),
  })
  .strict()
  .superRefine((item, ctx) => refineRecordSpec(item, ctx));
const recordItemSchema = z.union([recordReferenceSchema, inlineRecordItemSchema]);`
    : `const recordItemSchema = z
  .object({
    metadata: recordMetadataSchema.optional(),
    spec: z.record(z.string(), z.unknown()),
  })
  .strict()
  .superRefine((item, ctx) => refineRecordSpec(item, ctx));`;
  const singularRecordSchema = supportsRecordEnvelope
    ? `
export const recordSchema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("${recordEnvelopeKind}"),
    metadata: z
      .object({
        name: z.string().trim().min(1),
        namespace: z.string().trim().min(1),
        labels: z.record(z.string(), z.string()).optional(),
        annotations: z.record(z.string(), z.string()).optional(),
        action: z.enum(["PUT", "PATCH", "POST"]).optional(),
        selector: z.record(z.string(), z.unknown()).optional(),
      })
      .strict(),
    spec: ${recordSpecName}Spec,
  })
  .strict();

export type ${recordEnvelopeKind}Envelope = z.infer<typeof recordSchema>;
export type ${recordEnvelopeKind}Input = Omit<${recordEnvelopeKind}Envelope, "apiVersion" | "kind">;

function parse${recordEnvelopeKind}(value: unknown): ${recordEnvelopeKind}Envelope {
  const result = recordSchema.safeParse(value);
  if (!result.success) {
    throw new Error(\`${recordEnvelopeKind} is malformed at \${firstIssuePath(result.error)}.\`);
  }
  return result.data;
}

function new${recordEnvelopeKind}(input: ${recordEnvelopeKind}Input): ${recordEnvelopeKind}Envelope {
  return parse${recordEnvelopeKind}({
    apiVersion: INTAKE_API_VERSION,
    kind: "${recordEnvelopeKind}",
    ...input,
  });
}

async function read${recordEnvelopeKind}(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions = {},
): Promise<${recordEnvelopeKind}Envelope> {
  const ref = resolveReadPath(pathOrRef, options);
  if (ref.kind !== undefined && ref.kind !== "${recordEnvelopeKind}") {
    throw new Error(\`${recordEnvelopeKind} ref.kind \${ref.kind} does not match expected kind ${recordEnvelopeKind}: \${ref.filePath}\`);
  }
  const { contents, document } = await readYamlDocumentFile(ref.filePath, "${recordEnvelopeKind}");
  if (ref.sha256 !== undefined && yamlDigest(contents) !== ref.sha256) {
    throw new Error(\`${recordEnvelopeKind} sha256 mismatch: \${ref.filePath}\`);
  }
  const envelope = parse${recordEnvelopeKind}(document);
  if (
    options.expectedNamespace !== undefined &&
    envelope.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`${recordEnvelopeKind} namespace \${envelope.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${ref.filePath}\`,
    );
  }
  return envelope;
}

async function write${recordEnvelopeKind}(
  directory: string,
  envelope: ${recordEnvelopeKind}Envelope,
): Promise<{ path: string; sha256: string }> {
  const parsed = parse${recordEnvelopeKind}(envelope);
  const filePath = yamlResourcePath(directory, parsed);
  const contents = await writeYamlDocumentFile(filePath, parsed);
  return { path: filePath, sha256: yamlDigest(contents) };
}
`
    : "";
  const readRecords = supportsRecordEnvelope
    ? `    if ("ref" in recordItem) {
      const record = await read${recordEnvelopeKind}(recordItem.ref, {
        relativeTo: filePath,
        expectedNamespace: artifact.metadata.namespace,
      });
      if (record.metadata.name !== recordKey) {
        throw new Error(
          \`${kind} record metadata.name \${record.metadata.name} does not match expected record key \${recordKey}: \${filePath}\`,
        );
      }
      records[recordKey] = {
        metadata: toRecordMetadata(recordKey, record.metadata),
        spec: validateRecord(filePath, recordKey, record.spec, record.metadata.action),
      };
    } else {
      records[recordKey] = {
        metadata: toRecordMetadata(recordKey, recordItem.metadata),
        spec: validateRecord(filePath, recordKey, recordItem.spec, recordItem.metadata?.action),
      };
    }`
    : `    records[recordKey] = {
      metadata: toRecordMetadata(recordKey, recordItem.metadata),
      spec: validateRecord(filePath, recordKey, recordItem.spec, recordItem.metadata?.action),
    };`;
  const externalizeRecords = supportsRecordEnvelope
    ? `  if (options.externalizeRecords === true) {
    const recordsDirectory =
      options.recordsDirectory ??
      \`\${path.basename(artifactPath, path.extname(artifactPath))}.records\`;
    const records: Record<string, { ref: { path: string; kind: "${recordEnvelopeKind}"; sha256?: string } }> = {};

    for (const [recordKey, recordItem] of Object.entries(artifact.spec.records)) {
      if ("ref" in recordItem) {
        records[recordKey] = recordItem;
        continue;
      }
      const record = new${recordEnvelopeKind}({
        metadata: {
          name: recordKey,
          namespace: artifact.metadata.namespace,
          ...(recordItem.metadata?.action !== undefined
            ? { action: recordItem.metadata.action }
            : {}),
          ...(recordItem.metadata?.selector !== undefined
            ? { selector: recordItem.metadata.selector }
            : {}),
        },
        spec: recordItem.spec as z.infer<typeof ${recordSpecName}Spec>,
      });
      const recordPath = path.join(
        path.dirname(artifactPath),
        recordsDirectory,
        yamlResourceFileName(recordKey, "${recordEnvelopeKind}"),
      );
      const contents = await writeYamlDocumentFile(recordPath, record);
      records[recordKey] = {
        ref: {
          path: path.relative(path.dirname(artifactPath), recordPath),
          kind: "${recordEnvelopeKind}",
          sha256: yamlDigest(contents),
        },
      };
    }

    artifact = new${kind}({
      metadata: artifact.metadata,
      spec: {
        ...artifact.spec,
        records,
      },
    });
  }`
    : `  if (options.externalizeRecords === true) {
    throw new Error("${kind} does not support externalized singular record envelopes.");
  }`;
  const singularRecordExport = supportsRecordEnvelope
    ? `
export const ${recordEnvelopeKind} = {
  kind: "${recordEnvelopeKind}",
  schema: recordSchema,
  new: new${recordEnvelopeKind},
  read: read${recordEnvelopeKind},
  write: write${recordEnvelopeKind},
};
`
    : "";
  return `${generatedHeader()}import path from "node:path";
import { z } from "zod";
import { INTAKE_API_VERSION } from "../intake-api-version.js";
import {
  firstIssuePath,
  yamlDigest,
  yamlResourceFileName,
  yamlResourcePath,
} from "../resource.js";
import {
  readYamlDocumentFile,
  writeYamlDocumentFile,
} from "../internal/yaml-document.js";
import { ${recordSpecName}Spec } from "./entity-specs.js";
export { ${recordSpecName}Spec } from "./entity-specs.js";

${envelopeSupport(kind)}

const metadataSchema = z
  .object({
    name: z.string().trim().min(1),
    namespace: z.string().trim().min(1),
    labels: z.record(z.string(), z.string()).optional(),
    annotations: z.record(z.string(), z.string()).optional(),
    createdAt: z.string().trim().min(1).optional(),
    producedAt: z.string().trim().min(1).optional(),
    producer: z.string().trim().min(1).optional(),
  })
  .strict();

// A record's own metadata (ADR 0034): the write verb and the addressing, kept with
// the record — never folded into the spec (the spec is only the payload). Default
// action is PUT (upsert by name). A record carries only what it needs; the resolver
// enforces the per-verb constraints (PUT⟹name, PATCH⟹name xor selector, POST⟹neither).
const recordMetadataSchema = z
  .object({
    action: z.enum(["PUT", "PATCH", "POST"]).optional(),
    name: z.string().trim().min(1).optional(),
    selector: z.record(z.string(), z.unknown()).optional(),
  })
  .strict();
export type RecordMetadata = z.infer<typeof recordMetadataSchema>;

// A record's spec validates against the full entity spec for PUT/POST (a create
// needs its required fields) and against a partial for PATCH (only the fields being
// set — a partial update). ADR 0034. The partial keeps the strict mode, so an
// unknown column is still rejected under every verb.
function recordSpecSchema(action?: "PUT" | "PATCH" | "POST") {
  return action === "PATCH" ? ${recordSpecName}Spec.partial() : ${recordSpecName}Spec;
}
function refineRecordSpec(
  item: { metadata?: { action?: "PUT" | "PATCH" | "POST" }; spec: unknown },
  ctx: z.RefinementCtx,
): void {
  const result = recordSpecSchema(item.metadata?.action).safeParse(item.spec);
  if (!result.success) {
    for (const issue of result.error.issues) {
      ctx.addIssue({ ...issue, path: ["spec", ...issue.path] });
    }
  }
}

${recordItemSchema}

export const schema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("${kind}"),
    metadata: metadataSchema,
    spec: z
      .object({
        warnings: z.array(z.string()).optional(),
        audit: z.record(z.string(), z.unknown()).optional(),
        records: z.record(z.string(), recordItemSchema),
      })
      .strict(),
  })
  .strict();

export type ${kind}Envelope = z.infer<typeof schema>;
export type ${kind}Input = Omit<${kind}Envelope, "apiVersion" | "kind">;
export type ${kind}ResolvedEnvelope = Omit<${kind}Envelope, "spec"> & {
  spec: Omit<${kind}Envelope["spec"], "records"> & {
    records: Record<
      string,
      { metadata: RecordMetadata; spec: z.infer<typeof ${recordKind}Spec> }
    >;
  };
};

export type ImportArtifactWriteOptions = {
  externalizeRecords?: boolean;
  recordsDirectory?: string;
};

function parse${kind}(value: unknown): ${kind}Envelope {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new Error(formatError(result.error));
  }
  return result.data;
}

function new${kind}(input: ${kind}Input): ${kind}Envelope {
  return parse${kind}({
    apiVersion: INTAKE_API_VERSION,
    kind: "${kind}",
    ...input,
  });
}

function validateRecord(
  artifactPath: string,
  recordKey: string,
  value: unknown,
  action?: "PUT" | "PATCH" | "POST",
): z.infer<typeof ${recordSpecName}Spec> {
  const result = recordSpecSchema(action).safeParse(value);
  if (!result.success) {
    throw new Error(
      \`${kind} record \${recordKey} is malformed at \${firstIssuePath(result.error)}: \${artifactPath}\`,
    );
  }
  return result.data as z.infer<typeof ${recordSpecName}Spec>;
}

// The record's metadata, kept with it through resolution (ADR 0034). The record
// key is its name; the write verb + addressing (action/selector) ride along when
// present. Works for both an inline item's metadata and a resolved record
// envelope's metadata (both optionally carry action/selector).
function toRecordMetadata(
  recordKey: string,
  metadata?: { action?: "PUT" | "PATCH" | "POST"; selector?: Record<string, unknown> },
): RecordMetadata {
  return {
    name: recordKey,
    ...(metadata?.action !== undefined ? { action: metadata.action } : {}),
    ...(metadata?.selector !== undefined ? { selector: metadata.selector } : {}),
  };
}

${singularRecordSchema}

async function read${kind}(
  filePath: string,
  options: EnvelopeReadOptions & {
    expectedKind?: "${kind}";
    expectedSha256?: string;
    raw: true;
  },
): Promise<${kind}Envelope>;
async function read${kind}(
  filePath: string,
  options?: EnvelopeReadOptions & {
    expectedKind?: "${kind}";
    expectedSha256?: string;
    raw?: false;
  },
): Promise<${kind}ResolvedEnvelope>;
async function read${kind}(
  filePath: string,
  options: EnvelopeReadOptions & {
    expectedKind?: "${kind}";
    expectedSha256?: string;
    raw?: boolean;
  } = {},
): Promise<${kind}Envelope | ${kind}ResolvedEnvelope> {
  const { contents, document } = await readYamlDocumentFile(filePath, "${kind}");
  if (options.expectedSha256 !== undefined && yamlDigest(contents) !== options.expectedSha256) {
    throw new Error(\`${kind} sha256 mismatch: \${filePath}\`);
  }
  const artifact = parse${kind}(document);
  if (options.expectedKind !== undefined && artifact.kind !== options.expectedKind) {
    throw new Error(\`${kind} kind \${artifact.kind} does not match expected kind \${options.expectedKind}: \${filePath}\`);
  }
  if (
    options.expectedNamespace !== undefined &&
    artifact.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`${kind} namespace \${artifact.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${filePath}\`,
    );
  }
  if (options.raw === true) {
    return artifact;
  }

  const records: Record<
    string,
    { metadata: RecordMetadata; spec: z.infer<typeof ${recordSpecName}Spec> }
  > = {};
  for (const [recordKey, recordItem] of Object.entries(artifact.spec.records)) {
${readRecords}
  }

  return {
    ...artifact,
    spec: {
      ...artifact.spec,
      records,
    },
  };
}

async function write${kind}(
  directory: string,
  envelope: ${kind}Input,
  options: ImportArtifactWriteOptions = {},
): Promise<{ path: string; sha256: string }> {
  let artifact = new${kind}(envelope);
  const artifactPath = yamlResourcePath(directory, artifact);

${externalizeRecords}

  const contents = await writeYamlDocumentFile(artifactPath, artifact);
  return { path: artifactPath, sha256: yamlDigest(contents) };
}

export const ${kind} = {
  kind: "${kind}",
  schema,
  new: new${kind},
  read: read${kind},
  write: write${kind},
};

${singularRecordExport}

export const read = read${kind};
export const write = write${kind};
`;
}

function artifactsModule(): string {
  const artifactImports = IMPORT_ARTIFACT_KINDS.map(
    (kind) => `import { ${kind} } from "./${kind}.js";`,
  ).join("\n");
  const artifactSpecSchemas = IMPORT_ARTIFACT_KINDS.map(
    (kind) => `  ${kind}: ${kind}.schema.shape.spec,`,
  ).join("\n");
  return `${generatedHeader()}import path from "node:path";
import { z } from "zod";
import { INTAKE_API_VERSION } from "../intake-api-version.js";
import { IMPORT_ARTIFACT_KINDS } from "../import-types.js";
import {
  firstIssuePath,
  yamlDigest,
  yamlResourcePath,
} from "../resource.js";
import {
  readYamlDocumentFile,
  writeYamlDocumentFile,
} from "../internal/yaml-document.js";
${artifactImports}

${envelopeSupport("Artifacts")}

const metadataSchema = z
  .object({
    name: z.string().trim().min(1),
    namespace: z.string().trim().min(1),
    labels: z.record(z.string(), z.string()).optional(),
    annotations: z.record(z.string(), z.string()).optional(),
    producedAt: z.string().trim().min(1).optional(),
    producer: z.string().trim().min(1).optional(),
  })
  .strict();

const artifactKindSchema = z.enum(IMPORT_ARTIFACT_KINDS);
const artifactSpecSchemas: Record<string, z.ZodType> = {
${artifactSpecSchemas}
};
const artifactReferenceSchema = z
  .object({
    ref: z
      .object({
        path: z.string().trim().min(1),
        kind: artifactKindSchema,
        sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(),
      })
      .strict(),
  })
  .strict();
const inlineArtifactSchema = z
  .object({
    kind: artifactKindSchema,
    spec: z.record(z.string(), z.unknown()),
  })
  .strict()
  .superRefine((artifact, context) => {
    const specSchema = artifactSpecSchemas[artifact.kind];
    const result = specSchema.safeParse(artifact.spec);
    if (!result.success) {
      for (const issue of result.error.issues) {
        context.addIssue({ ...issue, path: ["spec", ...issue.path] });
      }
    }
  });

export const schema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("Artifacts"),
    metadata: metadataSchema,
    spec: z
      .object({
        artifacts: z
          .array(
            z.union([artifactReferenceSchema, inlineArtifactSchema]),
          ),
      })
      .strict(),
  })
  .strict();

export type ArtifactsEnvelope = z.infer<typeof schema>;
export type ArtifactsInput = Omit<z.infer<typeof schema>, "apiVersion" | "kind">;

function parseArtifacts(value: unknown): ArtifactsEnvelope {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new Error(formatError(result.error));
  }
  return result.data;
}

function newArtifacts(input: ArtifactsInput): ArtifactsEnvelope {
  return parseArtifacts({
    apiVersion: INTAKE_API_VERSION,
    kind: "Artifacts",
    ...input,
  });
}

async function readArtifacts(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions = {},
): Promise<ArtifactsEnvelope> {
  const ref = resolveReadPath(pathOrRef, options);
  if (ref.kind !== undefined && ref.kind !== "Artifacts") {
    throw new Error(\`Artifacts ref.kind \${ref.kind} does not match expected kind Artifacts: \${ref.filePath}\`);
  }
  const { contents, document } = await readYamlDocumentFile(ref.filePath, "Artifacts");
  if (ref.sha256 !== undefined && yamlDigest(contents) !== ref.sha256) {
    throw new Error(\`Artifacts sha256 mismatch: \${ref.filePath}\`);
  }
  const envelope = parseArtifacts(document);
  if (
    options.expectedNamespace !== undefined &&
    envelope.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`Artifacts namespace \${envelope.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${ref.filePath}\`,
    );
  }
  return envelope;
}

async function writeArtifacts(
  directory: string,
  envelope: ArtifactsEnvelope,
): Promise<{ path: string }> {
  const parsed = parseArtifacts(envelope);
  const filePath = yamlResourcePath(directory, parsed);
  await writeYamlDocumentFile(filePath, parsed);
  return { path: filePath };
}

export const Artifacts = {
  kind: "Artifacts",
  schema,
  new: newArtifacts,
  read: readArtifacts,
  write: writeArtifacts,
};

export async function read(
  filePath: string,
  options: Parameters<typeof Artifacts.read>[1] = {},
) {
  return Artifacts.read(filePath, options);
}

export async function write(directory: string, envelope: ArtifactsInput) {
  return Artifacts.write(directory, Artifacts.new(envelope));
}
`;
}

function mutationKind(recordKind: string, operation: ImportOperation): string {
  return `${recordKind}${IMPORT_OPERATION_SUFFIXES[operation]}`;
}

function specName(kind: ImportArtifactKind): string {
  return RECORD_KIND_BY_ARTIFACT_KIND[kind];
}

function mutationSpecExpression(
  specBaseName: string,
  operation: ImportOperation,
): string {
  if (operation === "create") {
    return `${specBaseName}CreateSpec`;
  }
  if (operation === "update") {
    return `z
  .object({
    operations: z.array(operationSchema).min(1),
  })
  .strict()`;
  }
  return "z.object({}).strict()";
}

function mutationModule(
  kind: ImportArtifactKind,
  operation: ImportOperation,
): string {
  const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
  const specBaseName = specName(kind);
  const envelopeKind = mutationKind(recordKind, operation);
  const specImport =
    operation === "create" || operation === "update"
      ? `import { ${specBaseName}Spec${operation === "create" ? `, ${specBaseName}CreateSpec` : ""} } from "../../../../../shared/io/generated/entity-specs.js";\n`
      : "";
  const operationImport = "";
  const updateValidation =
    operation === "update"
      ? `
const fieldSchemas = (${specBaseName}Spec as z.ZodObject<z.ZodRawShape>).shape;
const fieldNames = Object.keys(fieldSchemas);
const fieldSchemaByName: Record<string, { safeParse(value: unknown): { success: true } | { success: false; error: z.ZodError } }> = fieldSchemas as unknown as Record<string, { safeParse(value: unknown): { success: true } | { success: false; error: z.ZodError } }>;

const mutationOperationSourceSchema = z
  .object({
    namespace: z.string().trim().min(1),
    command: z
      .object({
        name: z.string().trim().min(1),
      })
      .strict(),
    kind: z.string().trim().min(1),
    name: z.string().trim().min(1),
  })
  .strict();

const mutationOperationEvidenceSchema = z.array(z.record(z.string(), z.unknown()));

const mutationOperationBaseSchema = z
  .object({
    path: z
      .string()
      .trim()
      .min(1)
      .refine((value) => value.split(".").every((part) => part.length > 0), {
        message: "Path segments must not be empty",
      }),
    reason: z.string().trim().min(1),
    source: mutationOperationSourceSchema,
    evidence: mutationOperationEvidenceSchema.optional(),
  })
  .strict();

const operationSchema = z.union([
  mutationOperationBaseSchema.extend({
    action: z.literal("set"),
    from: z.unknown(),
    to: z.unknown(),
  }).strict(),
  mutationOperationBaseSchema.extend({
    action: z.literal("check"),
    value: z.unknown(),
  }).strict(),
]).superRefine(
  (operation, context) => {
    if (operation.path.includes(".")) {
      context.addIssue({
        code: "custom",
        path: ["path"],
        message: "must be a ${recordKind} field",
      });
      return;
    }
    const fieldSchema = fieldSchemaByName[operation.path];
    if (fieldSchema === undefined) {
      context.addIssue({
        code: "custom",
        path: ["path"],
        message: \`must be one of \${fieldNames.join(", ")}\`,
      });
      return;
    }
    if (operation.action === "set") {
      for (const propertyName of ["from", "to"] as const) {
        if (propertyName === "from" && operation.from === undefined) {
          continue;
        }
        const result = fieldSchema.safeParse(operation[propertyName]);
        if (!result.success) {
          for (const issue of result.error.issues) {
            context.addIssue({ ...issue, path: [propertyName, ...issue.path] });
          }
        }
      }
      return;
    }

    const result = fieldSchema.safeParse(operation.value);
    if (!result.success) {
      for (const issue of result.error.issues) {
        context.addIssue({ ...issue, path: ["value", ...issue.path] });
      }
    }
  },
);
`
      : "";
  return `${generatedHeader()}import path from "node:path";
import { z } from "zod";
import { INTAKE_API_VERSION } from "../../../../../shared/io/intake-api-version.js";
import {
  firstIssuePath,
  yamlDigest,
  yamlResourcePath,
} from "../../../../../shared/io/resource.js";
import {
  readYamlDocumentFile,
  writeYamlDocumentFile,
} from "../../../../../shared/io/internal/yaml-document.js";
${specImport}${operationImport}
${envelopeSupport(envelopeKind)}
const metadataSchema = z
  .object({
    name: z.string().trim().min(1),
    namespace: z.string().trim().min(1),
    labels: z.record(z.string(), z.string()).optional(),
    annotations: z.record(z.string(), z.string()).optional(),
  })
  .strict();

${updateValidation}

export const specSchema = ${mutationSpecExpression(specBaseName, operation)};

export const schema = z
  .object({
    apiVersion: z.literal(INTAKE_API_VERSION),
    kind: z.literal("${envelopeKind}"),
    metadata: metadataSchema,
    spec: specSchema,
  })
  .strict();

export type ${envelopeKind}Envelope = z.infer<typeof schema>;
export type ${envelopeKind}Input = Omit<${envelopeKind}Envelope, "apiVersion" | "kind">;

function parse${envelopeKind}(value: unknown): ${envelopeKind}Envelope {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new Error(formatError(result.error));
  }
  return result.data;
}

function new${envelopeKind}(input: ${envelopeKind}Input): ${envelopeKind}Envelope {
  return parse${envelopeKind}({
    apiVersion: INTAKE_API_VERSION,
    kind: "${envelopeKind}",
    ...input,
  });
}

async function read${envelopeKind}(
  pathOrRef: string | EnvelopeReadRef,
  options: EnvelopeReadOptions = {},
): Promise<${envelopeKind}Envelope> {
  const ref = resolveReadPath(pathOrRef, options);
  if (ref.kind !== undefined && ref.kind !== "${envelopeKind}") {
    throw new Error(\`${envelopeKind} ref.kind \${ref.kind} does not match expected kind ${envelopeKind}: \${ref.filePath}\`);
  }
  const { contents, document } = await readYamlDocumentFile(ref.filePath, "${envelopeKind}");
  if (ref.sha256 !== undefined && yamlDigest(contents) !== ref.sha256) {
    throw new Error(\`${envelopeKind} sha256 mismatch: \${ref.filePath}\`);
  }
  const envelope = parse${envelopeKind}(document);
  if (
    options.expectedNamespace !== undefined &&
    envelope.metadata.namespace !== options.expectedNamespace
  ) {
    throw new Error(
      \`${envelopeKind} namespace \${envelope.metadata.namespace} does not match expected namespace \${options.expectedNamespace}: \${ref.filePath}\`,
    );
  }
  return envelope;
}

async function write${envelopeKind}(
  directory: string,
  envelope: ${envelopeKind}Envelope,
): Promise<{ path: string }> {
  const parsed = parse${envelopeKind}(envelope);
  const filePath = yamlResourcePath(directory, parsed);
  await writeYamlDocumentFile(filePath, parsed);
  return { path: filePath };
}

export const ${envelopeKind} = {
  kind: "${envelopeKind}",
  schema,
  new: new${envelopeKind},
  read: read${envelopeKind},
  write: write${envelopeKind},
};
`;
}

function mutationIndexModule(): string {
  const imports: string[] = [];
  const mapItems: string[] = [];
  // Every importable kind maps to a database table (each descriptor has one).
  for (const kind of IMPORT_ARTIFACT_KINDS) {
    const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
    for (const operation of IMPORT_OPERATIONS) {
      const envelopeKind = mutationKind(recordKind, operation);
      imports.push(`import { ${envelopeKind} } from "./${envelopeKind}.js";`);
      mapItems.push(`  ${envelopeKind},`);
    }
  }
  return `${generatedHeader()}${imports.join("\n")}

export const importMutationEnvelopeTypes = {
${mapItems.join("\n")}
};
`;
}

function indexModule(): string {
  const artifactExports = IMPORT_ARTIFACT_KINDS.map((kind) => {
    const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
    if (!supportsRecordEnvelopeFor(kind)) {
      return `export { ${kind}, ${recordKind}Spec } from "./${kind}.js";
export type { ${kind}Envelope, ${kind}Input } from "./${kind}.js";`;
    }
    const recordEnvelopeKind = recordEnvelopeKindFor(kind);
    return `export { ${kind}, ${recordEnvelopeKind}, ${recordKind}Spec } from "./${kind}.js";
export type { ${kind}Envelope, ${kind}Input, ${recordEnvelopeKind}Envelope, ${recordEnvelopeKind}Input } from "./${kind}.js";`;
  }).join("\n");
  return `${generatedHeader()}export { Artifacts } from "./Artifacts.js";
export type { ArtifactsEnvelope, ArtifactsInput } from "./Artifacts.js";
${artifactExports}
`;
}

// A uniform per-kind module registry (envelope, record spec, read, write) so the
// hand io layer builds its maps by looping over this — no kind enumerated by hand.
function artifactModulesModule(): string {
  const imports = IMPORT_ARTIFACT_KINDS.map((kind) => {
    const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
    return `import { ${kind}, ${recordKind}Spec, read as read${kind}, write as write${kind} } from "./${kind}.js";`;
  }).join("\n");
  const entries = IMPORT_ARTIFACT_KINDS.map((kind) => {
    const recordKind = RECORD_KIND_BY_ARTIFACT_KIND[kind];
    return `  ${kind}: { envelope: ${kind}, recordSpec: ${recordKind}Spec, read: read${kind}, write: write${kind} },`;
  }).join("\n");
  return `${generatedHeader()}${imports}

export const ARTIFACT_MODULES = {
${entries}
} as const;
`;
}

const databaseUrl = process.env.DATABASE_URL;
if (databaseUrl === undefined || databaseUrl.trim() === "") {
  throw new Error(
    "DATABASE_URL is required: envelope specs are generated by introspecting the database schema so the two can never drift.",
  );
}
const schema = await introspectSchema(databaseUrl, ENTITY_TABLES);

await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });
await rm(importMutationOutputDirectory, { recursive: true, force: true });
await mkdir(importMutationOutputDirectory, { recursive: true });
await writeFile(
  path.join(outputDirectory, "entity-specs.ts"),
  generateEntitySpecsModule(schema, generatedHeader()),
);
await writeFile(path.join(outputDirectory, "Artifacts.ts"), artifactsModule());
for (const kind of IMPORT_ARTIFACT_KINDS) {
  await writeFile(
    path.join(outputDirectory, `${kind}.ts`),
    artifactModule(kind),
  );
  for (const operation of IMPORT_OPERATIONS) {
    await writeFile(
      path.join(
        importMutationOutputDirectory,
        `${mutationKind(RECORD_KIND_BY_ARTIFACT_KIND[kind], operation)}.ts`,
      ),
      mutationModule(kind, operation),
    );
  }
}
await writeFile(
  path.join(outputDirectory, "artifact-modules.ts"),
  artifactModulesModule(),
);
await writeFile(path.join(outputDirectory, "index.ts"), indexModule());
await writeFile(
  path.join(importMutationOutputDirectory, "index.ts"),
  mutationIndexModule(),
);

console.log(`Generated envelope types in ${outputDirectory}`);
