import { writeFile } from "node:fs/promises";
import path from "node:path";
import { introspectSchema } from "./lib/schema-introspection.js";
import { ENTITY_TABLES } from "./lib/entity-spec-generator.js";
import { generateDataRequestDoc } from "./lib/data-request-doc-generator.js";

const databaseUrl = process.env.DATABASE_URL;
if (databaseUrl === undefined || databaseUrl.trim() === "") {
  throw new Error(
    "DATABASE_URL is required: the data-request document is generated by introspecting the database schema so the two can never drift.",
  );
}

const schema = await introspectSchema(databaseUrl, ENTITY_TABLES);
const outputPath = path.join(process.cwd(), "docs", "data-request-format.md");
await writeFile(outputPath, generateDataRequestDoc(schema));
console.log(`Wrote ${outputPath}`);
