-- Bring the database schema into exact, strict sync with the intake envelope
-- specs. The specs are generated by introspecting this schema
-- (scripts/generate-envelope-types.ts): a column's non-blank CHECK becomes a
-- `nonEmptyString` field; its absence becomes a plain `z.string()`. To keep the
-- two locked together — and because a blank string is never a valid value (use
-- NULL for "absent") — every text column carries a non-blank CHECK in the exact
-- `char_length(btrim(col)) > 0` form the generator parses. NOT NULL text →
-- `char_length(btrim(col)) > 0`; nullable text → `col IS NULL OR
-- char_length(btrim(col)) > 0`. Strict first: it is easier to relax a
-- constraint later than to add one.
--
-- Nullability is deliberately NOT tightened here: agency.latitude/longitude stay
-- nullable (federal agencies carry no coordinates in production). The one
-- exception is agency_officers.agency_id, which the AgencyPersonnel spec
-- requires — an assignment must belong to an agency.

-- agency ---------------------------------------------------------------------
alter table public.agency
  add constraint agency_id_not_blank check (char_length(btrim(id)) > 0),
  add constraint agency_name_not_blank check (char_length(btrim(name)) > 0),
  add constraint agency_state_not_blank check (char_length(btrim(state)) > 0),
  add constraint agency_slug_not_blank check (char_length(btrim(slug)) > 0),
  add constraint agency_location_path_id_not_blank
    check (char_length(btrim(location_path_id)) > 0),
  add constraint agency_city_not_blank
    check (city is null or char_length(btrim(city)) > 0),
  add constraint agency_address_not_blank
    check (address is null or char_length(btrim(address)) > 0),
  add constraint agency_zip_code_not_blank
    check (zip_code is null or char_length(btrim(zip_code)) > 0),
  add constraint agency_contact_name_not_blank
    check (contact_name is null or char_length(btrim(contact_name)) > 0),
  add constraint agency_contact_email_not_blank
    check (contact_email is null or char_length(btrim(contact_email)) > 0);

-- agency_officers ------------------------------------------------------------
alter table public.agency_officers
  alter column agency_id set not null,
  add constraint agency_officers_id_not_blank check (char_length(btrim(id)) > 0),
  add constraint agency_officers_agency_id_not_blank
    check (char_length(btrim(agency_id)) > 0),
  add constraint agency_officers_officer_id_not_blank
    check (char_length(btrim(officer_id)) > 0),
  add constraint agency_officers_title_not_blank
    check (char_length(btrim(title)) > 0),
  add constraint agency_officers_badge_number_not_blank
    check (badge_number is null or char_length(btrim(badge_number)) > 0),
  add constraint agency_officers_license_id_not_blank
    check (license_id is null or char_length(btrim(license_id)) > 0);

-- license --------------------------------------------------------------------
alter table public.license
  add constraint license_id_not_blank check (char_length(btrim(id)) > 0),
  add constraint license_officer_id_not_blank
    check (char_length(btrim(officer_id)) > 0),
  add constraint license_license_type_not_blank
    check (char_length(btrim(license_type)) > 0),
  add constraint license_issued_by_authority_id_not_blank
    check (char_length(btrim(issued_by_authority_id)) > 0),
  add constraint license_status_not_blank
    check (status is null or char_length(btrim(status)) > 0);

-- license_action -------------------------------------------------------------
alter table public.license_action
  add constraint license_action_id_not_blank check (char_length(btrim(id)) > 0),
  add constraint license_action_license_id_not_blank
    check (char_length(btrim(license_id)) > 0),
  add constraint license_action_action_not_blank
    check (char_length(btrim(action)) > 0),
  add constraint license_action_status_not_blank
    check (status is null or char_length(btrim(status)) > 0);

-- licensing_authority --------------------------------------------------------
alter table public.licensing_authority
  add constraint licensing_authority_id_not_blank
    check (char_length(btrim(id)) > 0),
  add constraint licensing_authority_name_not_blank
    check (char_length(btrim(name)) > 0),
  add constraint licensing_authority_location_path_id_not_blank
    check (char_length(btrim(location_path_id)) > 0),
  add constraint licensing_authority_abbreviation_not_blank
    check (abbreviation is null or char_length(btrim(abbreviation)) > 0),
  add constraint licensing_authority_website_not_blank
    check (website is null or char_length(btrim(website)) > 0);

-- location_path --------------------------------------------------------------
alter table public.location_path
  add constraint location_path_location_path_id_not_blank
    check (char_length(btrim(location_path_id)) > 0),
  add constraint location_path_path_not_blank
    check (char_length(btrim(path)) > 0),
  add constraint location_path_state_or_territory_slug_not_blank
    check (char_length(btrim(state_or_territory_slug)) > 0),
  add constraint location_path_state_or_territory_name_not_blank
    check (char_length(btrim(state_or_territory_name)) > 0),
  add constraint location_path_administrative_area_slug_not_blank
    check (administrative_area_slug is null
      or char_length(btrim(administrative_area_slug)) > 0),
  add constraint location_path_place_slug_not_blank
    check (place_slug is null or char_length(btrim(place_slug)) > 0),
  add constraint location_path_administrative_area_name_not_blank
    check (administrative_area_name is null
      or char_length(btrim(administrative_area_name)) > 0),
  add constraint location_path_place_name_not_blank
    check (place_name is null or char_length(btrim(place_name)) > 0),
  add constraint location_path_parent_location_path_id_not_blank
    check (parent_location_path_id is null
      or char_length(btrim(parent_location_path_id)) > 0);

-- location_path_alias --------------------------------------------------------
alter table public.location_path_alias
  add constraint location_path_alias_alias_path_not_blank
    check (char_length(btrim(alias_path)) > 0),
  add constraint location_path_alias_location_path_id_not_blank
    check (char_length(btrim(location_path_id)) > 0);

-- location_path_geometry -----------------------------------------------------
alter table public.location_path_geometry
  add constraint location_path_geometry_location_path_id_not_blank
    check (char_length(btrim(location_path_id)) > 0);

-- officers -------------------------------------------------------------------
-- first_name, last_name, slug already carry non-blank checks.
alter table public.officers
  add constraint officers_id_not_blank check (char_length(btrim(id)) > 0),
  add constraint officers_middle_name_not_blank
    check (middle_name is null or char_length(btrim(middle_name)) > 0),
  add constraint officers_prefix_not_blank
    check (prefix is null or char_length(btrim(prefix)) > 0),
  add constraint officers_suffix_not_blank
    check (suffix is null or char_length(btrim(suffix)) > 0),
  add constraint officers_deceased_source_not_blank
    check (deceased_source is null or char_length(btrim(deceased_source)) > 0),
  add constraint officers_deceased_message_not_blank
    check (deceased_message is null or char_length(btrim(deceased_message)) > 0);
